woowa-techcamp-2021/deal-5

.eslintrc, .prettierrc, babel.config.json, package-lock.json, package.json, src/app.ts, src/pages/main.html, src/routers/index.ts, tsconfig.json, webpack.config.js
- 패키지 설치
- 초기 라우팅 세팅
- 페이지별 html 파일 생성
- eslint, prettier 적용
=> feat: 초기 세팅

server/app.ts, server/package-lock.json, server/package.json, server/routers/index.ts
=> chore: client, server 리팩토링

README.md
=> fix : readme 충돌 수정

client/package-lock.json, client/package.json, client/src/index.ts, client/src/pages/main/MainHeader.ts, client/src/scss/index.scss, client/src/scss/main.scss, client/src/scss/root.scss
=> add: 공통 scss 추가, 디렉토리 구조 수정

client/src/pages/components/commonHeader.ts, client/src/scss/index.scss, client/src/scss/root.scss, client/src/utils/createElem.ts
commonHeader scss 추가하구
index.scss 에서 root.scss 뺏습니다 !
=> feat : commonHeader SCSS 수정

client/package-lock.json, client/package.json, client/src/pages/components/commonHeader.ts, client/src/utils/createElem.ts
* `webpack-dev-server`, `@types/webpack-dev-server` 패키지 추가
* `HTMLElementAttrs` 인터페이스 수정
=> chore: 패키지 추가, HTMLElementAttrs 인터페이스 수정

client/src/scss/root.scss
width 값을 100%로 주다보니
padding 값도 포함되서 나타난 오류였습니다 :)
=> fix : 상품상세 페이지 버튼 수정

client/src/components/ItemDetail/ItemDetail.ts, client/src/components/ItemDetail/ItemDetailBody.ts, client/src/components/ItemDetail/ItemDetailFooter.ts, client/src/components/ItemDetail/Slider.ts, client/src/components/Share/DropDown.ts, client/src/components/main/BookmarkList.ts, client/src/components/main/Main.ts, client/src/components/main/Mainbody.ts, client/src/components/main/SalesList.ts, client/src/index.ts, client/src/scss/itemDetail.scss, client/src/scss/main.scss, client/src/scss/root.scss
시간순 !!
1. 메인페이지 각 탭 href 추가
2. 사이드바 백그라운드추가 : 클릭시 사이드바 class 토글
3. 사이드바가 열리고 왼쪽 화살표 svg를 눌렀을때 제대로 안닫히는 현상 수정
4. 사이드바 북마크 렌더링 될때마다 이벤트리스너가 중복해서 생성되는 오류 수정
5. <b>중요 ! 드랍다운</b> 수정
- 1. 드랍다운이 열리고 스크롤이 고정되도록 수정
- 2. 왼쪽에 드랍다운이 생길경우 화면밖으로 나가는 현상 수정
6. 메인페이지 메뉴 사이드바 판매목록 드랍다운이 제대로 보여지지 않는 현상 수정
7. 상품상세페이지 
- select로 진행시 option ui 변경이 어려운 점을 고려햐여 드랍다운 형태로 변경
=> [#42] feat : 메인페이지, 드랍다운, 상품상세 수정

client/src/components/core/Router.ts, client/src/index.ts
라우터에 파라미터 전달 기능 추가했습니다.
컴포넌트에서 받을 때는 props에서 `parsingData`로 받으시면 됩니다!
=> [#59] feat: 라우터에 파라미터 전달 기능 추가

server/action/user.ts, server/app.ts, server/db/index.ts, server/package-lock.json, server/package.json, server/query/user.ts, server/routers/index.ts, server/routers/user.ts
=> [#54] feat: 서버 구조 셋팅

client/src/apis/main.ts, client/src/components/Share/Snackbar.ts, client/src/components/main/Item.ts, client/src/components/main/Mainbody.ts, client/src/scss/root.scss, server/action/main.ts, server/query/main.ts, server/routers/index.ts, server/routers/main.ts
1. server api 추가
- 북마크 업데이트
- 아이템리스트 가져오기
2. 스낵바 추가하여 fetch 함수 response message가 넣어질수 있도록함
3. 프론트 main 페이지 리팩토링
=> feat : Main API 기능 추가

server/db/index.ts
기존 conn() 함수 때문에 
계속해서 createPool이 생성되어 나타난 현상
=> fix : TO MANY CONNECTION 오류 수정

client/src/apis/main.ts, client/src/assets/utils/fetchTemplets.ts, client/src/components/main/BookmarkList.ts, client/src/components/main/CategoryBody.ts, client/src/components/main/Item.ts, client/src/components/main/MainHeader.ts, client/src/components/main/Mainbody.ts, client/src/components/main/Menu.ts, client/src/components/main/SalesList.ts, client/src/scss/main.scss, client/src/scss/root.scss, server/action/main.ts, server/query/main.ts, server/routers/main.ts
=> repactor : main 페이지

server/action/refresh.ts, server/action/user.ts, server/routers/middlewares.ts, server/utils/jwtAuth.ts
변수 이름 불일치 수정하였습니다.
바로 머지하겠습니다!!
=> style: 변수 이름 불일치 수정

client/src/apis/main.ts, client/src/components/main/CategoryBody.ts, client/src/components/main/Main.ts, client/src/components/main/Mainbody.ts, client/src/components/main/SalesList.ts, server/action/main.ts, server/action/user.ts, server/app.ts, server/query/main.ts, server/routers/main.ts
1. 메인 화면 인피니티 스크롤
2. 카테고리별 아이템 목록
3. 쿠키파서제거
4. setcookie secure 옵션 제거
5. origin ec2 url 추가
=> [#64] feat : 메인 기능 추가

server/db/index.ts
=> fix : query실행 함수 수정

client/src/apis/main.ts, client/src/components/Share/Snackbar.ts, client/src/components/main/BookmarkList.ts, client/src/components/main/Main.ts, client/src/components/main/MainHeader.ts, client/src/components/main/Mainbody.ts, client/src/scss/main.scss, server/action/main.ts, server/query/main.ts, server/routers/main.ts
1. 스낵바 수정
2. 현재위치 input으로 태그변환
3. location 변경 작업
=> repactor: 메인화면 리팩토링

client/src/apis/itemdetail.ts, client/src/components/ItemDetail/ItemDetail.ts, client/src/components/main/Main.ts, client/src/components/main/MainHeader.ts, client/src/components/main/Mainbody.ts, client/src/scss/main.scss, client/src/scss/root.scss, server/action/itemdetail.ts, server/action/main.ts, server/query/itemdetail.ts, server/query/main.ts, server/routers/index.ts, server/routers/itemdetail.ts
유저 위치 변경기능
1. location 변경시 dispatch로 강제로 이벤트를 발생시킴
2. main body에서 이벤트를 추가하여 이벤트 감지가 될경우 setState변경 -> 리렌더링
- 본인 상품의 경우 location 이 변경되어도 계속해서 화면에 나타남 query문에서 본인상품 제외하고 보여주는 것도 나쁘지 않을듯..합니다!
=> feat: 유저 위치 변경 기능

client/src/apis/itemdetail.ts, client/src/apis/main.ts, client/src/assets/utils/fetchTemplets.ts, client/src/components/ItemDetail/ItemDetail.ts, client/src/components/ItemDetail/ItemDetailBody.ts, client/src/components/ItemDetail/Slider.ts, client/src/components/Share/DropDown.ts, client/src/components/main/BookmarkList.ts, client/src/components/main/SalesList.ts, client/src/scss/itemDetail.scss, server/action/itemdetail.ts, server/action/main.ts, server/query/itemdetail.ts, server/query/main.ts, server/routers/itemdetail.ts, server/routers/main.ts
1. 상세페이지 판매자일 때 상품 상태관리
2. 메뉴화면 및 상품상세페이지 상품삭제
3. 북마크 컴포넌트 전환 href 수정
4. 드롭다운 스페셜 아이템 기능 추가 (기존 드롭다운 컴포넌트에 영향 없음)
5. 삭제된 아이템 선택시 자동으로 삭제되었습니다 스낵바이후 history 전환
6. mysql 에서 1000단위 콤마 및 '원' 추가해서 데이터 반환
7. fetch 템플릿 delete용 템플릿 추가
=> feat : 상품 상세 페이지 및 상품 삭제기능 추가

client/src/apis/chat.ts, client/src/components/ChatDetail/ChatBar.ts, client/src/components/ChatDetail/ChatDetail.ts, client/src/components/ChatDetail/Chatting.ts, client/src/components/ChatDetail/InfoProduct.ts, client/src/components/ItemDetail/ItemDetailFooter.ts, client/src/components/ItemDetail/Slider.ts, client/src/components/Share/Button.ts, client/src/components/Share/ChatsList.ts, client/src/components/Share/ChatsListItem.ts, client/src/components/main/MainHeader.ts, client/src/scss/chatDetail.scss, client/src/scss/root.scss, server/action/chat.ts, server/action/newpost.ts, server/action/user.ts, server/app.ts, server/chat/chat.ts, server/query/chat.ts, server/routers/chat.ts, server/routers/index.ts, server/routers/middlewares.ts
0. 웹소켓 셋팅
1. 채팅방별 채팅 기능
2. 채팅 리스트 불러오기
3. 안읽은 카운트 세기
4. 채팅방에서 엔터 누를시 자동 전송
5. 채팅방 나가기
6. 문의하기 버튼 채팅방 새로 만들기
기타등등...
=> feat : 채팅 기능 구현
